# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kafeman < Formula
  desc ""
  homepage ""
  version "0.0.16"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Worldbug/kafeman/releases/download/v0.0.16/kafeman_0.0.16_Darwin_x86_64.tar.gz"
      sha256 "0cebbda5d8b2ba65edc296b76d3d1db94aa73836ceaadd05112147432d3cf330"

      def install
        bin.install "kafeman"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Worldbug/kafeman/releases/download/v0.0.16/kafeman_0.0.16_Darwin_arm64.tar.gz"
      sha256 "7c82199ca2dd9af44f5337ab7c9b90bb7ca15fcc50f6559c936adac2ccd89ff2"

      def install
        bin.install "kafeman"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Worldbug/kafeman/releases/download/v0.0.16/kafeman_0.0.16_Linux_arm64.tar.gz"
      sha256 "2c0c595511027cbbe4a23d34f036563d23771d622a09805898b390595f3d7032"

      def install
        bin.install "kafeman"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Worldbug/kafeman/releases/download/v0.0.16/kafeman_0.0.16_Linux_x86_64.tar.gz"
      sha256 "92df513823e3439ac5b9e6fe0702450add5d590e72c3dce9e2faa23e23e91e77"

      def install
        bin.install "kafeman"
      end
    end
  end
end
